### PR TITLE
Version 2.2.15

### PR DESCRIPTION
**Pull request by maaprote**
That's the definitive 2.2.15 version to test.

### CODE REVIEW

**Comment by kharissulistiyo** [comment]
I did test out this release. The theme's welcome box looks not styled as seen in below screenshot. Perhaps relevant styling lines are missing?

Screen Shot 2024-12-11 at 09 37 40

---
My testing environment:

```
### wp-core ###

version: 6.7.1
site_language: en_US
user_language: en_US
timezone: +00:00
permalink: /%year%/%monthnum%/%day%/%postname%/
https_status: true
multisite: false
user_registration: 0
blog_public: 1
default_comment_status: open
environment_type: production
user_count: 1
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /home/sitr4466/public_html/home_dir_release21520971.sitebox.my.id
wordpress_size: 56.94 MB (59701203 bytes)
uploads_path: /home/sitr4466/public_html/home_dir_release21520971.sitebox.my.id/wp-content/uploads
uploads_size: 32.29 KB (33064 bytes)
themes_path: /home/sitr4466/public_html/home_dir_release21520971.sitebox.my.id/wp-content/themes
themes_size: 19.88 MB (20846880 bytes)
plugins_path: /home/sitr4466/public_html/home_dir_release21520971.sitebox.my.id/wp-content/plugins
plugins_size: 28.00 B (28 bytes)
fonts_path: /home/sitr4466/public_html/home_dir_release21520971.sitebox.my.id/wp-content/uploads/fonts
fonts_size: directory not found
database_size: 2.13 MB (2228224 bytes)
total_size: 78.97 MB (82809399 bytes)

### wp-active-theme ###

name: Botiga (botiga)
version: 2.2.15
author: aThemes
author_website: https://athemes.com
parent_theme: none
theme_features: core-block-patterns, widgets-block-editor, automatic-feed-links, title-tag, post-thumbnails, menus, post-formats, html5, custom-background, customize-selective-refresh-widgets, custom-logo, align-wide, editor-color-palette, editor-font-sizes, responsive-embeds, block-templates, appearance-tools, custom-header, widgets
theme_path: /home/sitr4466/public_html/home_dir_release21520971.sitebox.my.id/wp-content/themes/botiga
auto_update: Disabled

### wp-themes-inactive (2) ###

Twenty Twenty-Five: version: 1.0, author: the WordPress team, Auto-updates disabled
Twenty Twenty-Four: version: 1.3, author: the WordPress team, Auto-updates disabled

### wp-media ###

image_editor: WP_Image_Editor_GD
imagick_module_version: Not available
imagemagick_version: Not available
imagick_version: Not available
file_uploads: 1
post_max_size: 10M
upload_max_filesize: 10M
max_effective_size: 10 MB
max_file_uploads: 20
gd_version: bundled (2.1.0 compatible)
gd_formats: GIF, JPEG, PNG, WebP, BMP, XPM
ghostscript_version: unknown

### wp-server ###

server_architecture: Linux 5.14.0-427.42.1.el9_4.x86_64 x86_64
httpd_software: LiteSpeed
php_version: 7.4.33 64bit
php_sapi: litespeed
max_input_variables: 1000
time_limit: 30
memory_limit: 256M
max_input_time: 60
upload_max_filesize: 10M
php_post_max_size: 10M
curl_version: 7.76.1 OpenSSL/3.2.2
suhosin: false
imagick_availability: false
pretty_permalinks: true
htaccess_extra_rules: true
current: 2024-12-11T02:38:58+00:00
utc-time: Wednesday, 11-Dec-24 02:38:58 UTC
server-time: 2024-12-11T02:38:56+00:00

### wp-database ###

extension: mysqli
server_version: 10.11.10-MariaDB-cll-lve
client_version: mysqlnd 7.4.33
max_allowed_packet: 268435456
max_connections: 512

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /home/sitr4466/public_html/home_dir_release21520971.sitebox.my.id/wp-content
WP_PLUGIN_DIR: /home/sitr4466/public_html/home_dir_release21520971.sitebox.my.id/wp-content/plugins
WP_MEMORY_LIMIT: 40M
WP_MAX_MEMORY_LIMIT: 256M
WP_DEBUG: false
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: false
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_ENVIRONMENT_TYPE: undefined
WP_DEVELOPMENT_MODE: undefined
DB_CHARSET: utf8mb4
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable
fonts: not writable

```

**Comment by maaprote** [comment]
Thanks @kharissulistiyo! However, I couldn't reproduce the same here. It seems to work fine on my end (the file isn't empty). Did you download the .zip from Slack #releases channel?

**Comment by kharissulistiyo** [comment]
@maaprote thanks for reviewing.

> _Did you download the .zip from Slack #releases channel?_

No, I didn't.

I got the theme package from Develop branch: https://github.com/athemes/Botiga/tree/develop.

**Comment by kharissulistiyo** [comment]
Hi @maaprote,

I just tested out the latest release https://github.com/athemes/Botiga/releases/tag/v2.2.15

I can confirm that the mentioned issue above doesn't appear.

**Pull request merged**
